### ISSUE TITLE
2N7002DW pin assignment incorrect

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/CubeSat-Radio-v0.1#13]
Component pin assignment is incorrect. Please read datasheet https://www.diodes.com/assets/Datasheets/ds30120.pdf

TX and 3V6 indicator LEDs do not work because of this.

**Comment by TobiNakamura** [comment]
Fixed, please review

**Comment by liquiddandruff** [comment]
Can also paste commit hash to reference the commit too ;)  e4fd6992

**Comment by Alenux55** [comment]
![sot-363 check](https://cloud.githubusercontent.com/assets/24886818/26616596/ac909db8-4584-11e7-9811-81c4a33599a9.png)
Part is mirrored. Please update symbol and make footprint mapping as follows:
6  5  4
1  2  3

**Comment by TobiNakamura** [comment]
ef6c72adf7fbf4c4be107657a5a16833a87c14b3

**Comment by Alenux55** [comment]
Checked, looks good
![sot-363 check](https://cloud.githubusercontent.com/assets/24886818/26616887/b11877be-4586-11e7-92c6-6e3f6bc48ba9.png)
