### ISSUE TITLE
Check PC104 layout

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/CubeSat-Radio-v0.1#22]
Check board size, mechanical hole size, plating, position, connector position.

**Comment by Alenux55** [comment]
Comments:
-Board size is good
-Hole size, plating, and position is good
-Connector position looks good
![pc104-std_check](https://cloud.githubusercontent.com/assets/24886818/26716625/102b48ea-472f-11e7-81f2-646d1a84901a.png)
