### ISSUE TITLE
Check Connector Labeling

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/CubeSat-Radio-v0.1#23]
Check labels on jumpers, SMA connectors, PC/104 connector, test points.
I forgot to label the LEDs.

**Comment by TobiNakamura** [comment]
938609b44109fadba14369935545f2254597ae9c

**Comment by Alenux55** [comment]
- **W3** looks good on the **3.6 V** line
- **P3** looks good
    - Can we shorten the silkscreen from _AMP EN_ to _EN_? I think the text above the part conveys that it controls the amplifier
- **W2** looks good, but wouldn't it be better to connect to the center pin of P2 so we can check VPC from either source?
- **P2** looks good

![p2 p3 w2 w3 check](https://user-images.githubusercontent.com/24886818/26988776-77ea5580-4d05-11e7-88ac-ab3e42edecc4.png)

- **P4** looks good
- **W4** looks good
- **W1** looks good
    - Need to make sure we can configure GPIO2 of CC1101 to do this (see **table 41** setting **0x1C** in the datasheet for candidate; active low signal, active for **SLEEP** and **RX** states)

![p4 w4 w1 check](https://user-images.githubusercontent.com/24886818/26989788-3b194f5e-4d09-11e7-9454-5314d5a032ed.png)

- **J8** looks good
- **J9** looks good

![j8 j9 check](https://user-images.githubusercontent.com/24886818/26990447-6a1dee0c-4d0b-11e7-8cb7-3bac82c4ce36.png)

**Comment by TobiNakamura** [comment]
7a60c29a94ea7f9e260f3175538d6a2e0feaa4c7

**Comment by Alenux55** [comment]
Requested changes look good, closing
![w3 p3 w2 p2 check 2](https://user-images.githubusercontent.com/24886818/27007978-4b8f2702-4e1a-11e7-880a-62c9549d6c54.png)
