### ISSUE TITLE
Check Ground plane

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/CubeSat-Radio-v0.1#24]
Pay attention to copper islands.
Pay attention to return current paths especially for VCC_* and microstrip.

**Comment by Alenux55** [comment]
I'm a bit concerned about the possibility for acid traps with all the thermals:
![gerber check 1](https://user-images.githubusercontent.com/24886818/27112741-c707bc28-506d-11e7-8d4e-9649e50f71ec.png)

**Comment by TobiNakamura** [comment]
All ICs and some passives have been flooded.
