### ISSUE TITLE
Check RF path

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/CubeSat-Radio-v0.1#25]
![microstrip](https://user-images.githubusercontent.com/10017555/27006392-e86cb554-4de7-11e7-8f8e-7d2cdd783fdc.png)
Check CPWG, passives, wall of ground vias.

**Comment by TobiNakamura** [comment]
The substrait thickness is not 0.2mm, its 1.6mm.
The track width is a bit worrisome.
![image](https://user-images.githubusercontent.com/10017555/27006590-a13cbb84-4dec-11e7-8c8c-6fb456727c77.png)

**Comment by TobiNakamura** [comment]
![image](https://user-images.githubusercontent.com/10017555/27015146-5a6f08b2-4ebc-11e7-9bc5-fe3602644a85.png)

**Comment by TobiNakamura** [comment]
PCBWay confirmed that Dk is 3.8.
![calc](https://user-images.githubusercontent.com/10017555/27109769-b4165750-5059-11e7-824d-912a5e01a572.png)

**Comment by Alenux55** [comment]
Do we want to update the trace width to get it closer to **50 Ω**? At the current thickness, we'll get **52.5 Ω**

**Comment by Alenux55** [comment]
Also, do we want to add fencing vias along the RF traces? According to [this document](www.edn.com/Pdf/ViewPdf?contentItemId=4406491), if the vias are spaced less than about **2 inches**, we won't run into ground impedance issues.

Further, from the same document:
_Spacing the ground vias at 1/8th of a wavelength gives good isolation here also, but for the ultimate
isolation available (i.e., greater than the 120 dB that a modern network analyzer can measure) it has
been found that the via spacing should be kept to 1/20th of a wavelength or less._

In our case, **1/20** of the wavelength is about **3.5 cm**, which is easily doable.

**Comment by Alenux55** [comment]
Never mind about the via fencing

**Comment by TobiNakamura** [comment]
RF traces are now 0.6mm width with 0.2mm spacing to ground.
