### ISSUE TITLE
Need ability to probe desired points in RF path

### ISSUE THREAD

**Issue by Alenux55** [SFUSatClub/CubeSat-Radio-v0.1#3]
Add a vertical SMA population option between CC1125 and balun, balun and switch, and switch and front end

**Comment by Alenux55** [comment]
Also, make this a resistor population option, like a T-junction

**Comment by TobiNakamura** [comment]
Can the T-junction be made such that the placement of SMA can be selected facing towards or away from the font of the signal chain? Should there be 2 SMA footprints at each node in the signal chain; one for each direction?

**Comment by Alenux55** [comment]
Instead of one SMA for each direction, use a single 0402 SMA pad such that a jumper can be placed at 45 degrees in either direction:
![45_deg_pad](https://cloud.githubusercontent.com/assets/24886818/26616996/8843c748-4587-11e7-9cff-69bae8356ba8.png)

**Comment by TobiNakamura** [comment]
![image](https://user-images.githubusercontent.com/10017555/27006794-1305252a-4df3-11e7-85db-28303c312a50.png)
Too weird?

**Comment by Alenux55** [comment]
What if we just make the rectangular pad into a square and rotate it 45 degrees?

**Comment by Alenux55** [comment]
Lets move this to the issue in KiCad-Lib since the main objective of this issue is complete. [https://github.com/SFUSatClub/KiCad-Lib/issues/13](https://github.com/SFUSatClub/KiCad-Lib/issues/13)
