### ISSUE TITLE
Adjust solder paste aperture sizes

### ISSUE THREAD

**Issue by Alenux55** [SFUSatClub/CubeSat-Radio-v0.1#4]
- Make passive apertures larger
- Make IC thermal aperture smaller

**Comment by TobiNakamura** [comment]
See KiCad-Lib for fixes. Have yet to make IC thermal aperture smaller

**Comment by TobiNakamura** [comment]
Made SKY65366 thermal pad aperture smaller

**Comment by Alenux55** [comment]
Do we want to move this to KiCad-Lib issues?

**Comment by TobiNakamura** [comment]
Yes but i can also be closed so...
