### ISSUE TITLE
Add club logo on silkscreen

### ISSUE THREAD

**Issue by Alenux55** [SFUSatClub/CubeSat-Radio-v0.1#5]

**Comment by Alenux55** [comment]
Added, but needs to be placed later

**Comment by TobiNakamura** [comment]
938609b44109fadba14369935545f2254597ae9c

**Comment by Alenux55** [comment]
![logo check](https://user-images.githubusercontent.com/24886818/26990755-a477d6a2-4d0c-11e7-9bf1-2e4654dd6f03.png)

![rg0bs1u](https://user-images.githubusercontent.com/24886818/26990817-dc257ffa-4d0c-11e7-87a9-45078b7f5523.gif)
