### ISSUE TITLE
Incorporate connector ESD connection

### ISSUE THREAD

**Issue by Alenux55** [SFUSatClub/CubeSat-Radio-v0.1#9]

**Comment by TobiNakamura** [comment]
Also for tactile switches and toggle switches and any other exposed interfaces

**Comment by TobiNakamura** [comment]
No ESD protection on CC debug connector or PC104 connector due to large number of pins. ESD suppression was placed on test points, jumpers, and potentiometers. 2d7826e3472c9caad9861fabc356ae1afd1395ca

**Comment by Alenux55** [comment]
- Are we relying on the LDOs as ESD protection from Vin?
- Do we need D10 if we have D9?

**Comment by TobiNakamura** [comment]
Vin is 5V, the knee of the TVS diodes are 5V or so. Yes, too cheap to get another TVS diodes, the LDO can burn. TVS should be on SKY input and on POT to protect 3v3 line.

**Comment by Alenux55** [comment]
Gotcha, because **R7** is close to **RV1**:
![d10 rv1 r7 check](https://user-images.githubusercontent.com/24886818/27015309-f618dc18-4ebf-11e7-9cc3-b5e99b095703.png)

And then none on **R8** because it's far from the jumper. Do we want any extra protection on P4 as it's attached to the debugger?

**Comment by TobiNakamura** [comment]
TVS diode added OP_3v3. 39e230a1014d43e301bcf52a7b34e85acb464f90
